// ─── ThemeStudio SDK — generated by ThemeStudioPlugin v1.1 ──────────────
// Vendored SDK version: 1.1
// DO NOT edit the two header lines above — the plugin uses them to detect version drift.
// You may freely edit everything below. Delete this file and re-run the plugin to regenerate.

import { validateTheme, resolveThemeDependencies, applyCustomTheme, mergeWithDefaults } from './theme-sdk';
import { BUNDLED_THEMES, BUNDLED_THEME_IDS } from '../sidepanel/themes';
import { THEME_DEFAULTS } from './theme-defaults';

export { BUNDLED_THEME_IDS };

const STORAGE_KEY = 'themeId';
const FALLBACK_ID = 'light';

/**
 * Load a theme by ID, merge with defaults, resolve font dependencies, and apply
 * it to the document root. Safe to call on every extension wakeup.
 */
export async function loadTheme(id) {
  const theme = BUNDLED_THEMES[id];
  if (!theme) {
    console.warn(`[useTheme] Unknown theme "${id}", falling back to "${FALLBACK_ID}"`);
    return loadTheme(FALLBACK_ID);
  }
  const error = validateTheme(theme);
  if (error) {
    console.error(`[useTheme] Invalid theme "${id}": ${error}`);
    return;
  }
  const merged = mergeWithDefaults(theme, THEME_DEFAULTS);
  await resolveThemeDependencies(merged);
  applyCustomTheme(merged);
}


/**
 * Persist the user's theme choice. Uses chrome.storage.local so the
 * selection survives extension reloads and is shared across all contexts.
 */
export async function persistTheme(id) {
  // Also mirror to localStorage for synchronous FOUC guard reads
  try { localStorage.setItem(STORAGE_KEY, id); } catch { /* non-fatal */ }
  await chrome.storage.local.set({ [STORAGE_KEY]: id });
}

/**
 * Read the persisted theme ID and apply it. Call once on extension startup.
 * Falls back to 'light' if no theme has been saved yet.
 */
export async function restoreTheme() {
  try {
    const result = await chrome.storage.local.get(STORAGE_KEY);
    const id = result[STORAGE_KEY] ?? FALLBACK_ID;
    await loadTheme(id);
  } catch {
    await loadTheme(FALLBACK_ID);
  }
}

// ── Auto-restore on module load ─────────────────────────────────────────────
// Runs as a module-level side effect the instant this file is imported.
// Import this file in your entry point — the stored theme is applied automatically.
restoreTheme();
