/**
 * Metadata and README builders for ZIP exports.
 */

import { formatDateHuman } from './format-helpers.js';

/**
 * Build the _metadata.json object for a ZIP export.
 *
 * @param {import('../tree.js').TopicTree} tree
 * @param {Object[]} chats
 * @returns {Object}
 */
export function buildMetadataJson(tree, chats) {
  const topicsMap = (tree && tree.topics) ? tree.topics : {};
  const allChats  = Array.isArray(chats) ? chats : [];

  // Source counts
  const sources = {};
  let firstChat = Infinity;
  let lastChat  = -Infinity;

  for (const chat of allChats) {
    const src = chat.source || 'unknown';
    sources[src] = (sources[src] || 0) + 1;
    if (chat.timestamp) {
      if (chat.timestamp < firstChat) firstChat = chat.timestamp;
      if (chat.timestamp > lastChat)  lastChat  = chat.timestamp;
    }
  }

  const topicsArr = Object.values(topicsMap).map(t => ({
    id:        t.id,
    name:      t.name,
    parentId:  t.parentId,
    chatCount: Array.isArray(t.chatIds) ? t.chatIds.length : 0
  }));

  return {
    export_version:  '1.0',
    export_date:     new Date().toISOString(),
    bainder_version: '1.0.0',
    tree_structure: {
      topics:       topicsArr,
      total_chats:  allChats.length,
      total_topics: topicsArr.length
    },
    statistics: {
      date_range: {
        first_chat: firstChat !== Infinity  ? new Date(firstChat).toISOString() : null,
        last_chat:  lastChat  !== -Infinity ? new Date(lastChat).toISOString()  : null,
      },
      sources
    }
  };
}

/**
 * Build a README.md string for the export archive.
 *
 * @param {{ exportDate: string, totalChats: number, totalTopics: number, format: string }} stats
 * @returns {string}
 */
export function buildReadme(stats) {
  const { exportDate, totalChats, totalTopics, format } = stats || {};
  const dateHuman = exportDate ? formatDateHuman(new Date(exportDate).getTime()) : 'Unknown';
  const ext = format === 'html' ? '.html' : '.md';

  return `# bAInder Export

This archive was exported from **bAInder**, an AI Chat Organizer browser extension.

## Export Details

- **Exported:** ${dateHuman}
- **Topics:** ${totalTopics || 0}
- **Chats:** ${totalChats || 0}
- **Format:** ${format === 'html' ? 'HTML' : 'Markdown'}

## Folder Structure

Each folder corresponds to a topic in your bAInder topic tree.
Sub-folders represent child topics.  Each \`${ext}\` file is a chat conversation.

- \`_topic.json\` — metadata for that topic (name, chat count, date range)
- \`_metadata.json\` — full tree structure and export statistics (root level)
- \`README.md\` — this file

## Searching Your Chats

**VS Code:** Open this folder and use \`Ctrl+Shift+F\` (Find in Files) to search all chats at once.

**Terminal / grep:**
\`\`\`bash
# Find chats mentioning "async await"
grep -r "async await" . --include="*${ext}" -l

# Show matching lines with context
grep -r "machine learning" . --include="*${ext}" -n -C 2
\`\`\`

## Re-importing

This archive can be re-imported into bAInder via the **Import from ZIP** option to restore
or merge your chat history on another device.

---

*Generated by bAInder v1.0.0*
`;
}
