// Auto-generated by ThemeStudioPlugin v1.1 — DO NOT EDIT
// Re-run ThemeStudioPlugin to add or refresh themes.

import argyle from './argyle.json';
import aurora from './aurora.json';
import battletoads from './battletoads.json';
import blueprint from './blueprint.json';
import cobalt from './cobalt.json';
import crosshatch from './crosshatch.json';
import crystal from './crystal.json';
import dark from './dark.json';
import drMario from './dr-mario.json';
import ember from './ember.json';
import forest from './forest.json';
import frost from './frost.json';
import glass from './glass.json';
import graphPaper from './graph-paper.json';
import haze from './haze.json';
import light from './light.json';
import mario from './mario.json';
import medieval from './medieval.json';
import megaman from './megaman.json';
import metroid from './metroid.json';
import mint from './mint.json';
import mosaic from './mosaic.json';
import neon from './neon.json';
import nord from './nord.json';
import oceanDepth from './ocean-depth.json';
import prism from './prism.json';
import retro from './retro.json';
import scifi from './scifi.json';
import smoke from './smoke.json';
import solarized from './solarized.json';
import sunset from './sunset.json';
import tartan from './tartan.json';
import terminal from './terminal.json';
import typewriter from './typewriter.json';
import vaporwave from './vaporwave.json';
import zelda from './zelda.json';

export const BUNDLED_THEMES = {
  'argyle': argyle,
  'aurora': aurora,
  'battletoads': battletoads,
  'blueprint': blueprint,
  'cobalt': cobalt,
  'crosshatch': crosshatch,
  'crystal': crystal,
  'dark': dark,
  'dr-mario': drMario,
  'ember': ember,
  'forest': forest,
  'frost': frost,
  'glass': glass,
  'graph-paper': graphPaper,
  'haze': haze,
  'light': light,
  'mario': mario,
  'medieval': medieval,
  'megaman': megaman,
  'metroid': metroid,
  'mint': mint,
  'mosaic': mosaic,
  'neon': neon,
  'nord': nord,
  'ocean-depth': oceanDepth,
  'prism': prism,
  'retro': retro,
  'scifi': scifi,
  'smoke': smoke,
  'solarized': solarized,
  'sunset': sunset,
  'tartan': tartan,
  'terminal': terminal,
  'typewriter': typewriter,
  'vaporwave': vaporwave,
  'zelda': zelda,
};

export const BUNDLED_THEME_IDS = Object.keys(BUNDLED_THEMES);